"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlbinosDuck = exports.SaxonDuck = exports.RubberDuck = exports.RedHeadDuck = exports.DecoyDuck = void 0;
var DecoyDuck_1 = require("./DecoyDuck");
Object.defineProperty(exports, "DecoyDuck", { enumerable: true, get: function () { return DecoyDuck_1.DecoyDuck; } });
var RedHeadDuck_1 = require("./RedHeadDuck");
Object.defineProperty(exports, "RedHeadDuck", { enumerable: true, get: function () { return RedHeadDuck_1.RedHeadDuck; } });
var RubberDuck_1 = require("./RubberDuck");
Object.defineProperty(exports, "RubberDuck", { enumerable: true, get: function () { return RubberDuck_1.RubberDuck; } });
var SaxonDuck_1 = require("./SaxonDuck");
Object.defineProperty(exports, "SaxonDuck", { enumerable: true, get: function () { return SaxonDuck_1.SaxonDuck; } });
var AlbinosDuck_1 = require("./AlbinosDuck");
Object.defineProperty(exports, "AlbinosDuck", { enumerable: true, get: function () { return AlbinosDuck_1.AlbinosDuck; } });
