"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RocketFlyBehavior = exports.RadioControlFlyBehavior = exports.WingsFlyBehavior = exports.DisableFlyBehavior = void 0;
var DisableFlyBehavior_1 = require("./DisableFlyBehavior");
Object.defineProperty(exports, "DisableFlyBehavior", { enumerable: true, get: function () { return DisableFlyBehavior_1.DisableFlyBehavior; } });
var WingsFlyBehavior_1 = require("./WingsFlyBehavior");
Object.defineProperty(exports, "WingsFlyBehavior", { enumerable: true, get: function () { return WingsFlyBehavior_1.WingsFlyBehavior; } });
var RadioControlFlyBehavior_1 = require("./RadioControlFlyBehavior");
Object.defineProperty(exports, "RadioControlFlyBehavior", { enumerable: true, get: function () { return RadioControlFlyBehavior_1.RadioControlFlyBehavior; } });
var RocketFlyBehavior_1 = require("./RocketFlyBehavior");
Object.defineProperty(exports, "RocketFlyBehavior", { enumerable: true, get: function () { return RocketFlyBehavior_1.RocketFlyBehavior; } });
